"""Build the complete Modelica model source string from a ProcessForge config.

The generated model is flat and self-contained — no Modelica Standard Library
imports. Stream variables follow the naming convention ``{stream}_{prop}``
where ``prop`` is T, P, F, or z_{comp}, all passed through ``_sanitize_name``.
"""
from __future__ import annotations

from ..fmu._fmi_vars import _sanitize_name
from ..fmu.builder import _get_outlets
from . import unit_equations as ueq


# ---------------------------------------------------------------------------
# Topology helpers
# ---------------------------------------------------------------------------

_TOPOLOGY_KEYS = {"type", "in", "out", "out_liq", "out_vap"}


def _get_inlet_streams(unit_cfg: dict) -> list[str]:
    """Return list of inlet stream names (handles single-string or list)."""
    raw = unit_cfg.get("in", [])
    if isinstance(raw, list):
        return raw
    return [raw]


def _collect_all_streams(config: dict) -> list[str]:
    """Return ordered list of every stream name referenced in the config."""
    seen: set[str] = set()
    ordered: list[str] = []

    def _add(name: str) -> None:
        if name and name not in seen:
            seen.add(name)
            ordered.append(name)

    for s in config.get("streams", {}):
        _add(s)
    for unit_cfg in config.get("units", {}).values():
        for s in _get_inlet_streams(unit_cfg):
            _add(s)
        for s in _get_outlets(unit_cfg):
            _add(s)
    return ordered


def _collect_unit_params(config: dict) -> dict[str, dict]:
    """Return {unit_name: {param_key: value}} for all numeric unit params."""
    result: dict[str, dict] = {}
    for unit_name, unit_cfg in config.get("units", {}).items():
        params = {
            k: v
            for k, v in unit_cfg.items()
            if k not in _TOPOLOGY_KEYS and isinstance(v, (int, float))
        }
        if params:
            result[unit_name] = params
    return result


# ---------------------------------------------------------------------------
# Flash K-value computation
# ---------------------------------------------------------------------------

def _compute_flash_K_values(
    cfg: dict, comps: list[str], T_feed: float, P_flash: float
) -> dict[str, float]:
    """Compute Raoult's-law K_i = P_sat_i(T_feed) / P_flash via CoolProp.

    Falls back to K=1 for any component whose saturation pressure cannot be
    retrieved (e.g. non-condensable gases outside CoolProp's range).
    """
    try:
        from CoolProp.CoolProp import PropsSI
    except ImportError:
        return {c: 1.0 for c in comps}

    K: dict[str, float] = {}
    for comp in comps:
        try:
            P_sat = PropsSI("P", "T", T_feed, "Q", 0, comp)
            K[comp] = P_sat / max(P_flash, 1.0)
        except Exception:
            K[comp] = 1.0
    return K


# ---------------------------------------------------------------------------
# Top-level builder
# ---------------------------------------------------------------------------

def build_model_source(
    model_name: str,
    config: dict,
    interface: dict,
) -> str:
    """Return a complete Modelica model as a string.

    Args:
        model_name:  Valid Modelica identifier (e.g. ``"PumpHeaterFlash"``).
        config:      Validated ProcessForge flowsheet config dict.
        interface:   Output of ``fmu.builder._analyze_config(config)``.

    Returns:
        Modelica model source (UTF-8 string).
    """
    comps: list[str] = interface["components"]
    unit_params: dict[str, dict] = _collect_unit_params(config)
    all_streams: list[str] = _collect_all_streams(config)
    feed_streams: list[str] = list(config.get("streams", {}).keys())
    feed_set: set[str] = set(feed_streams)

    has_tank = any(
        cfg.get("type") == "Tank" for cfg in config.get("units", {}).values()
    )

    lines: list[str] = [
        "// AUTO-GENERATED by processforge.modelica.transpiler — DO NOT EDIT",
        f"model {model_name}",
        "",
    ]

    # ------------------------------------------------------------------ parameters
    lines.append("  // ---- Unit parameters ----")
    for unit_name, params in unit_params.items():
        sn = _sanitize_name(unit_name)
        for key, val in params.items():
            sk = _sanitize_name(key)
            lines.append(f"  parameter Real {sn}_{sk} = {val!r};")
    # Flash units also need a P parameter even if not in numeric params
    for unit_name, unit_cfg in config.get("units", {}).items():
        if unit_cfg.get("type") == "Flash":
            sn = _sanitize_name(unit_name)
            P_val = unit_cfg.get("P", 101325.0)
            # Avoid duplicate if already emitted above
            if "P" not in unit_params.get(unit_name, {}):
                lines.append(f"  parameter Real {sn}_P = {P_val!r};")
            # Pre-computed K-values
            feed_T = _get_feed_T(config)
            K_vals = _compute_flash_K_values(
                unit_cfg, comps, T_feed=feed_T, P_flash=float(P_val)
            )
            for comp, K in K_vals.items():
                sc = _sanitize_name(comp)
                lines.append(f"  // K_{comp} = Psat({feed_T:.2f}K) / {P_val:.0f}Pa")

    lines.append("")

    # ------------------------------------------------------------------ stream variables
    lines.append("  // ---- Stream variables ----")
    for stream in all_streams:
        ss = _sanitize_name(stream)
        # Get start values from config if this is a feed stream
        start = config.get("streams", {}).get(stream, {})
        T_s = start.get("T", 298.15)
        P_s = start.get("P", 101325.0)
        F_s = start.get("flowrate", 1.0)
        lines.append(f'  Real {ss}_T(start={T_s!r}) "Temperature [K]";')
        lines.append(f'  Real {ss}_P(start={P_s!r}) "Pressure [Pa]";')
        lines.append(f'  Real {ss}_F(start={F_s!r}) "Molar flowrate [mol/s]";')
        z_start = start.get("z", {})
        for comp in comps:
            sc = _sanitize_name(comp)
            z_s = z_start.get(comp, 1.0 / max(len(comps), 1))
            lines.append(f"  Real {ss}_z_{sc}(start={z_s!r});")
        lines.append("")

    # ------------------------------------------------------------------ Tank ODE state variables
    if has_tank:
        lines.append("  // ---- Tank ODE state variables ----")
        for unit_name, unit_cfg in config.get("units", {}).items():
            if unit_cfg.get("type") != "Tank":
                continue
            sn = _sanitize_name(unit_name)
            initial_n = unit_cfg.get("initial_n", {})
            initial_T = unit_cfg.get("initial_T", 298.15)
            for comp in comps:
                sc = _sanitize_name(comp)
                n0 = float(initial_n.get(comp, 0.0))
                lines.append(
                    f"  Real tank_{sn}_n_{sc}(start={n0!r}, fixed=true);"
                )
            lines.append(
                f"  Real tank_{sn}_T_state(start={initial_T!r}, fixed=true);"
            )
            lines.append(f"  Real tank_{sn}_n_tot;")
        lines.append("")

    # ------------------------------------------------------------------ equation section
    lines.append("equation")
    lines.append("")

    # Feed boundary conditions
    lines.append("  // ---- Feed boundary conditions ----")
    for stream_name, stream_cfg in config.get("streams", {}).items():
        ss = _sanitize_name(stream_name)
        lines.append(f"  {ss}_T = {stream_cfg['T']!r};")
        lines.append(f"  {ss}_P = {stream_cfg['P']!r};")
        lines.append(f"  {ss}_F = {stream_cfg['flowrate']!r};")
        z = stream_cfg.get("z", {})
        for comp in comps:
            sc = _sanitize_name(comp)
            lines.append(f"  {ss}_z_{sc} = {z.get(comp, 0.0)!r};")
        lines.append("")

    # Unit equations
    lines.append("  // ---- Unit equations ----")
    for unit_name, unit_cfg in config.get("units", {}).items():
        unit_type = unit_cfg.get("type", "")
        inlets = _get_inlet_streams(unit_cfg)
        outlets = _get_outlets(unit_cfg)

        # Multi-inlet mixing → virtual merged stream
        merged_inlet: str
        if len(inlets) > 1:
            merged_inlet = f"__merged_{_sanitize_name(unit_name)}"
            # Declare merged stream variables
            # (we emit these as normal Real variables in the equation directly)
            lines += ueq.mixer_eq(inlets, merged_inlet, comps)
        else:
            merged_inlet = inlets[0] if inlets else ""

        # Retrieve pre-computed K-values for Flash
        if unit_type == "Flash":
            P_flash = float(unit_cfg.get("P", 101325.0))
            feed_T = _get_feed_T(config)
            K_vals = _compute_flash_K_values(unit_cfg, comps, T_feed=feed_T, P_flash=P_flash)

        # Dispatch
        if unit_type == "Pump":
            lines += ueq.pump_eq(unit_name, unit_cfg, merged_inlet, outlets[0], comps)
        elif unit_type == "Valve":
            lines += ueq.valve_eq(unit_name, unit_cfg, merged_inlet, outlets[0], comps)
        elif unit_type == "Heater":
            lines += ueq.heater_eq(unit_name, unit_cfg, merged_inlet, outlets[0], comps)
        elif unit_type == "Strainer":
            lines += ueq.strainer_eq(unit_name, unit_cfg, merged_inlet, outlets[0], comps)
        elif unit_type == "Pipes":
            lines += ueq.pipes_eq(unit_name, unit_cfg, merged_inlet, outlets[0], comps)
        elif unit_type == "Flash":
            out_vap = unit_cfg.get("out_vap", "")
            out_liq = unit_cfg.get("out_liq", "")
            lines += ueq.flash_eq(
                unit_name, unit_cfg, merged_inlet, out_vap, out_liq, comps, K_vals
            )
        elif unit_type == "Tank":
            lines += ueq.tank_eq(unit_name, unit_cfg, merged_inlet, outlets[0], comps)

        lines.append("")

    # If the multi-inlet merged streams reference variables not yet declared,
    # we need to declare them. Emit placeholder declarations at top.
    # (Handled by emitting them as equations — in flat Modelica, undeclared
    # intermediaries must be declared. We patch by prepending declarations.)
    merged_decls = _collect_merged_declarations(config, comps)
    if merged_decls:
        # Insert after the Tank state variables block
        insert_idx = lines.index("equation")
        for decl in reversed(merged_decls):
            lines.insert(insert_idx, decl)

    lines.append(f"end {model_name};")
    lines.append("")
    return "\n".join(lines)


def _get_feed_T(config: dict) -> float:
    """Return temperature from the first feed stream (used for Flash K-value computation)."""
    streams = config.get("streams", {})
    if streams:
        return float(next(iter(streams.values())).get("T", 298.15))
    return 298.15


def _collect_merged_declarations(config: dict, comps: list[str]) -> list[str]:
    """Emit variable declarations for virtual merged-inlet streams."""
    decls: list[str] = []
    for unit_name, unit_cfg in config.get("units", {}).items():
        inlets = _get_inlet_streams(unit_cfg)
        if len(inlets) <= 1:
            continue
        merged = f"__merged_{_sanitize_name(unit_name)}"
        decls.append(f"  // merged inlet for {unit_name}")
        decls.append(f'  Real {merged}_T(start=298.15) "merged inlet T";')
        decls.append(f'  Real {merged}_P(start=101325.0) "merged inlet P";')
        decls.append(f'  Real {merged}_F(start=1.0) "merged inlet F";')
        for comp in comps:
            sc = _sanitize_name(comp)
            decls.append(f"  Real {merged}_z_{sc}(start=0.5);")
    return decls
