"""Generate per-flowsheet FMU slave source code for PythonFMU."""
from __future__ import annotations

import json

from ._fmi_vars import _sanitize_name, get_fmi_variable_specs


def render_slave_source(
    slave_class_name: str,
    mode: str,
    backend: str,
    feed_streams: list[str],
    output_streams: list[str],
    components: list[str],
    unit_params: dict[str, dict],
    config: dict,
) -> str:
    """Return complete Python source for the per-flowsheet FMU slave.

    The generated file is stand-alone: ``_sanitize_name`` is embedded so the
    slave does not depend on processforge internals for name resolution.
    """
    specs = get_fmi_variable_specs(
        feed_streams, output_streams, components, unit_params, config, mode
    )

    lines: list[str] = []

    # ------------------------------------------------------------------ header
    lines += [
        "# AUTO-GENERATED by processforge.fmu.slave_template — DO NOT EDIT",
        "from __future__ import annotations",
        "import json",
        "import os",
        "import re",
        "from copy import deepcopy",
        "from pythonfmu import Fmi2Slave, Fmi2Causality, Fmi2Variability, Real",
        "",
        "",
        "def _sanitize_name(s: str) -> str:",
        '    return re.sub(r"[^a-zA-Z0-9_]", "_", s)',
        "",
        "",
        f"class {slave_class_name}(Fmi2Slave):",
        "",
        "    def __init__(self, **kwargs):",
        "        super().__init__(**kwargs)",
        "        _cfg_path = os.path.join(self.resources, 'flowsheet_config.json')",
        "        with open(_cfg_path) as _f:",
        "            self._config = json.load(_f)",
        "",
    ]

    # -------------------------------------------------------- instance attrs
    lines.append("        # --- instance attribute initial values ---")
    for spec in specs:
        lines.append(f"        self.{spec['attr_name']} = {spec['initial_value']!r}")

    lines.append("")

    # -------------------------------------------------------- register_variable
    lines.append("        # --- FMI variable registration ---")
    _causality_map = {
        "input": "Fmi2Causality.input",
        "output": "Fmi2Causality.output",
        "parameter": "Fmi2Causality.parameter",
    }
    _variability_map = {
        "continuous": "Fmi2Variability.continuous",
        "fixed": "Fmi2Variability.fixed",
    }
    for spec in specs:
        caus = _causality_map[spec["causality"]]
        var = _variability_map[spec["variability"]]
        desc = spec["description"].replace("'", "\\'")
        lines.append(
            f"        self.register_variable(Real("
            f"'{spec['attr_name']}', causality={caus}, "
            f"variability={var}, "
            f"description='{desc}'))"
        )

    lines.append("")

    # -------------------------------------------------------- embedded metadata
    components_repr = repr(components)
    feed_streams_repr = repr(feed_streams)
    output_streams_repr = repr(output_streams)
    # unit_params keys used for writing params back into config
    unit_param_keys_repr = repr({k: list(v.keys()) for k, v in unit_params.items()})
    tank_units = [n for n, c in config["units"].items() if c.get("type") == "Tank"]
    tank_units_repr = repr(tank_units)

    lines += [
        "        self._components = " + components_repr,
        "        self._feed_stream_names = " + feed_streams_repr,
        "        self._output_stream_names = " + output_streams_repr,
        "        self._unit_param_keys = " + unit_param_keys_repr,
        "        self._tank_units = " + tank_units_repr,
        "",
    ]

    if mode == "dynamic":
        lines += _render_dynamic_init(tank_units, components)

    # ---------------------------------------------------------- do_step
    lines.append("    def do_step(self, current_time: float, step_size: float) -> bool:")

    if mode == "steady":
        lines += _render_steady_do_step(backend)
    else:
        lines += _render_dynamic_do_step()

    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Steady-state do_step body
# ---------------------------------------------------------------------------

def _render_steady_do_step(backend: str) -> list[str]:
    return [
        f"        from processforge.eo import EOFlowsheet",
        "        config = deepcopy(self._config)",
        "",
        "        # Write FMI inputs → feed stream conditions",
        "        for _sn in self._feed_stream_names:",
        "            _ss = _sanitize_name(_sn)",
        "            config['streams'][_sn]['T'] = getattr(self, f'feed_{_ss}_T')",
        "            config['streams'][_sn]['P'] = getattr(self, f'feed_{_ss}_P')",
        "            config['streams'][_sn]['flowrate'] = getattr(self, f'feed_{_ss}_flowrate')",
        "            for _c in self._components:",
        "                _sc = _sanitize_name(_c)",
        "                config['streams'][_sn]['z'][_c] = getattr(self, f'feed_{_ss}_z_{_sc}')",
        "",
        "        # Write FMI parameters → unit design values",
        "        for _un, _pkeys in self._unit_param_keys.items():",
        "            _su = _sanitize_name(_un)",
        "            for _pk in _pkeys:",
        "                _spk = _sanitize_name(_pk)",
        "                _attr = f'param_{_su}_{_spk}'",
        "                if hasattr(self, _attr):",
        "                    config['units'][_un][_pk] = getattr(self, _attr)",
        "",
        f"        _fs = EOFlowsheet(config, backend='{backend}')",
        "        try:",
        "            _results = _fs.run()",
        "        except Exception:",
        "            return False",
        "",
        "        # Write solver results → FMI outputs",
        "        for _sn in self._output_stream_names:",
        "            _ss = _sanitize_name(_sn)",
        "            _stream = _results.get(_sn, {})",
        "            setattr(self, f'out_{_ss}_T', float(_stream.get('T', 0.0)))",
        "            setattr(self, f'out_{_ss}_P', float(_stream.get('P', 0.0)))",
        "            setattr(self, f'out_{_ss}_flowrate', float(_stream.get('flowrate', 0.0)))",
        "            for _c in self._components:",
        "                _sc = _sanitize_name(_c)",
        "                setattr(self, f'out_{_ss}_z_{_sc}',",
        "                        float(_stream.get('z', {}).get(_c, 0.0)))",
        "        return True",
    ]


# ---------------------------------------------------------------------------
# Dynamic __init__ tail and do_step body
# ---------------------------------------------------------------------------

def _render_dynamic_init(tank_units: list[str], components: list[str]) -> list[str]:
    lines = [
        "        # --- Build Flowsheet once for dynamic stepping ---",
        "        from processforge.flowsheet import Flowsheet as _Flowsheet",
        "        self._flowsheet = _Flowsheet(self._config)",
        "        self._flowsheet.build_units()",
        "        self._processing_order = self._flowsheet._get_processing_order()",
        "",
        "        # Initialise Tank state from config",
        "        self._tank_states = {}",
        "        for _un in self._tank_units:",
        "            _unit = self._flowsheet.units[_un]",
        "            _ucfg = self._config['units'][_un]",
        "            _init_n = _ucfg.get('initial_n', {})",
        "            self._tank_states[_un] = {",
        "                'n': {_c: float(_init_n.get(_c, 0.0)) for _c in self._components},",
        "                'T': float(_ucfg.get('initial_T', 298.15)),",
        "            }",
        "",
    ]
    return lines


def _render_dynamic_do_step() -> list[str]:
    return [
        "        # Build feed snapshots from FMI inputs",
        "        _current = {}",
        "        for _sn in self._feed_stream_names:",
        "            _ss = _sanitize_name(_sn)",
        "            _current[_sn] = {",
        "                'T': getattr(self, f'feed_{_ss}_T'),",
        "                'P': getattr(self, f'feed_{_ss}_P'),",
        "                'flowrate': getattr(self, f'feed_{_ss}_flowrate'),",
        "                'z': {_c: getattr(self, f'feed_{_ss}_z_{_sanitize_name(_c)}')",
        "                      for _c in self._components},",
        "            }",
        "",
        "        _components_set = set(self._components)",
        "",
        "        # Process units in topological order",
        "        for _un in self._processing_order:",
        "            _unit = self._flowsheet.units[_un]",
        "            _ucfg = self._config['units'][_un]",
        "            _inlet = self._flowsheet._get_merged_inlet(_current, _ucfg)",
        "",
        "            if _ucfg['type'] == 'Tank':",
        "                _outlet, self._tank_states[_un] = \\",
        "                    self._flowsheet._integrate_tank_step(",
        "                        _unit, _inlet, self._tank_states[_un],",
        "                        step_size, _components_set",
        "                    )",
        "            else:",
        "                _outlet = _unit.run(_inlet)",
        "",
        "            _outlet_name = _ucfg['out']",
        "            _current[_outlet_name] = _outlet",
        "",
        "        # Write stream results → FMI outputs",
        "        for _sn in self._output_stream_names:",
        "            _ss = _sanitize_name(_sn)",
        "            _stream = _current.get(_sn, {})",
        "            setattr(self, f'out_{_ss}_T', float(_stream.get('T', 0.0)))",
        "            setattr(self, f'out_{_ss}_P', float(_stream.get('P', 0.0)))",
        "            setattr(self, f'out_{_ss}_flowrate', float(_stream.get('flowrate', 0.0)))",
        "            for _c in self._components:",
        "                _sc = _sanitize_name(_c)",
        "                setattr(self, f'out_{_ss}_z_{_sc}',",
        "                        float(_stream.get('z', {}).get(_c, 0.0)))",
        "",
        "        # Write Tank state outputs",
        "        for _un, _state in self._tank_states.items():",
        "            _su = _sanitize_name(_un)",
        "            setattr(self, f'state_{_su}_T', float(_state['T']))",
        "            for _c in self._components:",
        "                _sc = _sanitize_name(_c)",
        "                setattr(self, f'state_{_su}_n_{_sc}',",
        "                        float(_state['n'].get(_c, 0.0)))",
        "",
        "        return True",
    ]
