"""Generate and manage docker-compose.yml for containerized providers."""
from __future__ import annotations

import os
import subprocess

from loguru import logger

COMPOSE_FILENAME = "docker-compose.yml"
COMPOSE_HEADER = (
    "# Auto-generated by pf init — do not edit manually.\n"
    "# Re-generate: pf init <flowsheet.json>\n"
)


def _compose_path(pf_dir: str) -> str:
    return os.path.join(pf_dir, COMPOSE_FILENAME)


def generate_compose(
    pf_dir: str,
    containerized_providers: dict[str, dict],
    outputs_dir: str = "outputs",
) -> None:
    """Generate docker-compose.yml for providers that need Docker.

    Args:
        pf_dir: Path to .processforge/ directory.
        containerized_providers: Dict of provider_name -> {"url": ..., "docker_image": ..., "port": ...}.
        outputs_dir: Host directory to mount as /data in containers.
    """
    if not containerized_providers:
        return

    lines = [COMPOSE_HEADER, "services:"]
    for name, info in containerized_providers.items():
        image = info["docker_image"]
        port = info.get("port") or 9000
        lines.append(f"  {name}:")
        lines.append(f"    image: {image}")
        # Bind directly to the host network so the provider is reachable at
        # http://localhost:<port>. Docker bridge port-publishing is unreliable
        # on some hosts (the published port is not reachable from the host),
        # and host networking avoids that entirely.
        lines.append(f"    network_mode: host")
        lines.append(f"    volumes:")
        lines.append(f'      - "${{PROCESSFORGE_OUTPUT_DIR:-{outputs_dir}}}:/data"')
        lines.append("")

    os.makedirs(pf_dir, exist_ok=True)
    path = _compose_path(pf_dir)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def start_provider_containers(pf_dir: str = ".processforge") -> bool:
    """Start provider containers via ``docker compose up -d``.

    Returns ``True`` if containers were started (or were already running),
    ``False`` if there is no compose file to act on or Docker is unavailable.
    """
    compose_path = _compose_path(pf_dir)
    if not os.path.exists(compose_path):
        return False
    try:
        result = subprocess.run(
            ["docker", "compose", "-f", compose_path, "up", "-d"],
            capture_output=True,
            text=True,
            timeout=180,
        )
    except FileNotFoundError:
        logger.warning(
            "Docker not found — cannot start provider containers. "
            "Install Docker or start providers manually."
        )
        return False
    except subprocess.TimeoutExpired:
        logger.warning("docker compose up timed out after 180s.")
        return False
    if result.returncode != 0:
        logger.warning(f"docker compose up failed: {result.stderr}")
        return False
    logger.info("Started provider container(s).")
    return True


def stop_provider_containers(pf_dir: str = ".processforge") -> None:
    """Stop and remove provider containers via ``docker compose down``.

    No-op when no compose file exists.
    """
    compose_path = _compose_path(pf_dir)
    if not os.path.exists(compose_path):
        return
    try:
        result = subprocess.run(
            ["docker", "compose", "-f", compose_path, "down"],
            capture_output=True,
            text=True,
            timeout=120,
        )
    except FileNotFoundError:
        logger.warning(
            "Docker not found — could not stop provider containers."
        )
        return
    except subprocess.TimeoutExpired:
        logger.warning("docker compose down timed out after 120s.")
        return
    if result.returncode != 0:
        logger.warning(f"docker compose down failed: {result.stderr}")
        return
    logger.info("Stopped provider container(s).")
