"""Generate docker-compose.yml for containerized providers."""
from __future__ import annotations

import os

COMPOSE_FILENAME = "docker-compose.yml"
COMPOSE_HEADER = (
    "# Auto-generated by pf init — do not edit manually.\n"
    "# Re-generate: pf init <flowsheet.json>\n"
)


def _compose_path(pf_dir: str) -> str:
    return os.path.join(pf_dir, COMPOSE_FILENAME)


def generate_compose(
    pf_dir: str,
    containerized_providers: dict[str, dict],
    outputs_dir: str = "outputs",
) -> None:
    """Generate docker-compose.yml for providers that need Docker.

    Args:
        pf_dir: Path to .processforge/ directory.
        containerized_providers: Dict of provider_name -> {"url": ..., "docker_image": ..., "port": ...}.
        outputs_dir: Host directory to mount as /data in containers.
    """
    if not containerized_providers:
        return

    lines = [COMPOSE_HEADER, "services:"]
    for name, info in containerized_providers.items():
        image = info["docker_image"]
        port = info.get("port") or 9000
        lines.append(f"  {name}:")
        lines.append(f"    image: {image}")
        lines.append(f"    ports:")
        lines.append(f'      - "{port}:{port}"')
        lines.append(f"    volumes:")
        lines.append(f'      - "${{PROCESSFORGE_OUTPUT_DIR:-{outputs_dir}}}:/data"')
        lines.append("")

    os.makedirs(pf_dir, exist_ok=True)
    path = _compose_path(pf_dir)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
